name: Campfire Android Test

on:
  workflow_dispatch:

jobs:
  build-campfire-android:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.9'
          channel: stable

      - name: Configure app
        working-directory: ${{ github.workspace }}/scripts
        run: |
          echo "yes" | ./build_app.sh \
            -v "0.0.1-test" \
            -b "1" \
            -p android \
            -a campfire \
            -d -s

      - name: Get dependencies
        working-directory: ${{ github.workspace }}
        run: flutter pub get

      - name: Build debug APK
        working-directory: ${{ github.workspace }}
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: campfire-android-debug
          path: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-debug.apk
